---
name: Submodule Updates

on:
  push

jobs:
  build:
    name: Submodule update
    runs-on: ubuntu-latest
    steps:
      - name: run action
        id: run_action
        uses: dragos.vacariu/github-action-create-commit-parent-submodule@v1
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          parent_repository: dragos.vacariu/Javascript-Projects
          parent_branch: main
