name: Update Submodule
on:
  repository_dispatch:
    types:
      - update-submodule
jobs:
  update-submodule:
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Authorize Git
        run: |
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name "$GITHUB_ACTOR"
      - name: Update submodule
        run: |
          git submodule update  --init --recursive --remote -f
      - name: Commit changes
        run: |
          git add writings
          git commit -m "Update submodule to latest commit"
          git push origin master
